apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nef-db.fullname" . }}
  labels:
    {{- include "nef-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName:  {{ include "nef-db.fullname" . }}
  selector:
    matchLabels:
      {{- include "nef-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nef-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.Postgres.image.repository }}:{{ .Values.Postgres.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.Postgres.image.pullPolicy }}
          ports:
            - name: postgres-http
              containerPort: {{ .Values.Postgres.service.port }}
              protocol: TCP
          args:
            - "-c"
            - "shared_buffers=256MB"
            - "-c"
            - "max_connections=200"
          envFrom:
            - configMapRef:
                name: db-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
