apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nef-mongo.fullname" . }}
  labels:
    {{- include "nef-mongo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName:  {{ include "nef-mongo.fullname" . }}
  selector:
    matchLabels:
      {{- include "nef-mongo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nef-mongo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.Mongo.image.repository }}:{{ .Values.Mongo.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.Mongo.image.pullPolicy }}
          ports:
            - name: mongo-http
              containerPort: {{ .Values.Mongo.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: mongo-config
