apiVersion: v1
kind: Service
metadata:
  name: {{ include "nef-mongo.fullname" . }}
  labels:
    {{- include "nef-mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.Mongo.service.type }}
  ports:
    - port: {{ .Values.Mongo.service.port }}
      targetPort: {{ .Values.Mongo.service.port }}
      protocol: TCP
      name: mongo-http
  selector:
    {{- include "nef-mongo.selectorLabels" . | nindent 4 }}
