apiVersion: v1
kind: Service
metadata:
  name: {{ include "nef-report.fullname" . }}
  labels:
    {{- include "nef-report.labels" . | nindent 4 }}
spec:
  type: {{ .Values.Report.service.type }}
  ports:
    - port: {{ .Values.Report.service.port }}
      targetPort: 80
      protocol: TCP
      name: report-http
  selector:
    {{- include "nef-report.selectorLabels" . | nindent 4 }}
