apiVersion: v1
kind: ConfigMap
metadata:
  name: report-config
data:
  SERVER_NAME: "localhost"
  SERVER_HOST: "localhost"
  SERVER_PORT: "8888"
  BACKEND_CORS_ORIGINS: '["http://localhost", "https://5g-api-emulator.medianetlab.eu"]'
  PROJECT_NAME: NEF_Emulator
  SECRET_KEY: 2D47CF2958CEC7CC86C988E9F9684
  FIRST_SUPERUSER: admin@my-email.com
  FIRST_SUPERUSER_PASSWORD: pass
  SMTP_TLS: "True"
  SMTP_PORT: "465"
  SMTP_HOST: mail.host.com
  SMTP_USER: user
  SMTP_PASSWORD: pass
  EMAILS_FROM_EMAIL: user@my-email.com
  SENTRY_DSN: ""
  USERS_OPEN_REGISTRATION: "true"
  REPORT_PATH: "../shared/report.json"