apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eechart.fullname" . }}
  labels:
{{ include "eechart.labels" . | indent 4 }}
spec:
  serviceName:  {{ include "eechart.fullname" . }} 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eechart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eechart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        vnf: {{ .Values.global.osm.vnf_id | lower}}
    spec:
      imagePullSecrets:
      - name: {{ include "eechart.fullname" . }}
      serviceAccountName: {{ template "eechart.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 8001
              protocol: TCP          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
          volumeMounts:
          - name: osm-ee
            mountPath: /app/storage  
          - name: osm-ee-source
            mountPath: /app/EE/osm_ee/vnf
      volumes:      
      - name: osm-ee-source
        configMap: 
          name:  {{ include "eechart.fullname" . }}
      - name: osm-ee
        emptyDir: {}